import { prisma } from "@/lib/prisma";
import { DEFAULT_BRAND_LOGO_BASE64, DEFAULT_BRAND_LOGO_MIME } from "@/lib/default-brand-logo";
import {
  SIGNATURE_ICON_EMAIL_BASE64,
  SIGNATURE_ICON_GLOBE_BASE64,
  SIGNATURE_ICON_LINKEDIN_BASE64,
  SIGNATURE_ICON_MIME,
  SIGNATURE_ICON_PHONE_BASE64,
} from "@/lib/signature-icons";

// Gmail-style HTML-table signature rendered from the user's UserProfile.
// Kept intentionally in one file so the render logic, the plain-text
// fallback, and the default-profile bootstrap are easy to grep for.
//
// Design principles:
// - HTML tables for layout (Gmail, Apple Mail, Outlook all handle tables
//   consistently; flexbox/grid are hit-or-miss in email clients).
// - Inline styles only — <style> blocks and class refs get stripped by
//   most email clients.
// - Logo as base64 data: URI so the recipient doesn't have to click
//   "Display images from this sender" to see it.
// - Icons as SVG data: URIs. Same reason + they stay crisp at any DPI.

export const SIGNATURE_GREEN = "#5A9642";
export const SIGNATURE_DARK = "#1a1a1a";
export const SIGNATURE_DIVIDER = "#e5e7eb";
export const MAX_LOGO_BYTES = 500 * 1024;

// Company LinkedIn page, rendered as a fixed bottom row in every
// signature (same for all BreakPoint users, so it's a constant rather
// than a per-user profile field). The row text reads "LinkedIn"; the
// link points here.
export const LINKEDIN_URL = "https://www.linkedin.com/company/breakpoint-talent";

export type UserProfileInput = {
  fullName: string;
  jobTitle: string;
  phone: string;
  website: string;
  logoDataBase64: string; // empty string means "no logo"
  logoMimeType: string;
};

export type UserProfileRecord = UserProfileInput & {
  userId: string;
  email: string;
  hasCustomLogo: boolean;
};

const ANDREW_DEFAULTS = {
  jobTitle: "Managing Partner & Founder",
  phone: "216-870-4655",
  website: "www.breakpointtalent.com",
};

// Default signature logo lives in src/lib/default-brand-logo.ts as a
// base64 constant compiled into the bundle. Reading from /public at
// runtime fails on Vercel serverless (the /public dir isn't shipped in
// the function bundle), so we never touch the filesystem here.
function loadDefaultLogo(): { mime: string; base64: string } {
  return { mime: DEFAULT_BRAND_LOGO_MIME, base64: DEFAULT_BRAND_LOGO_BASE64 };
}

// Fetch the user's profile, returning a fully-populated record with
// sensible defaults for missing fields. Never returns null; a signed-in
// user without a profile row gets a virtual one synthesized from their
// User row + /public/brand/ default logo.
export async function getUserBrandingProfile(userId: string): Promise<UserProfileRecord> {
  const user = await prisma.user.findUnique({
    where: { id: userId },
    select: { id: true, name: true, email: true, profile: true },
  });
  if (!user) {
    // Shouldn't happen in practice — caller already verified the session.
    // Fall back to the BreakPoint defaults so we never return null.
    const def = loadDefaultLogo();
    return {
      userId,
      email: "",
      fullName: "",
      jobTitle: ANDREW_DEFAULTS.jobTitle,
      phone: ANDREW_DEFAULTS.phone,
      website: ANDREW_DEFAULTS.website,
      logoDataBase64: def.base64,
      logoMimeType: def.mime,
      hasCustomLogo: false,
    };
  }
  const p = user.profile;
  const hasCustomLogo = Boolean(p?.logoData && p.logoData.length > 0);
  let logoDataBase64 = "";
  let logoMimeType = "";
  if (hasCustomLogo) {
    logoDataBase64 = Buffer.from(p!.logoData!).toString("base64");
    logoMimeType = p!.logoMimeType ?? "image/png";
  } else {
    const def = loadDefaultLogo();
    logoDataBase64 = def.base64;
    logoMimeType = def.mime;
  }
  return {
    userId: user.id,
    email: user.email ?? "",
    fullName: p?.fullName?.trim() || user.name?.trim() || "",
    jobTitle: p?.jobTitle?.trim() || ANDREW_DEFAULTS.jobTitle,
    phone: p?.phone?.trim() || ANDREW_DEFAULTS.phone,
    website: p?.website?.trim() || ANDREW_DEFAULTS.website,
    logoDataBase64,
    logoMimeType,
    hasCustomLogo,
  };
}

// PNG data: URI helpers. Switched from inline SVG to base64 PNG in
// Phase 6.5 because Gmail (and a handful of webmail clients) silently
// strips inline SVG src= refs, which left the icons rendering as empty
// outlined boxes in delivered email. PNG data URIs render reliably
// across every major client. Source bytes live in
// src/lib/signature-icons.ts (generated by scripts/generate-signature-
// icons.js — re-run that script if the artwork changes).
function pngDataUri(base64: string): string {
  return `data:${SIGNATURE_ICON_MIME};base64,${base64}`;
}

function envelopeIcon(): string {
  return pngDataUri(SIGNATURE_ICON_EMAIL_BASE64);
}

function phoneIcon(): string {
  return pngDataUri(SIGNATURE_ICON_PHONE_BASE64);
}

function globeIcon(): string {
  return pngDataUri(SIGNATURE_ICON_GLOBE_BASE64);
}

function linkedinIcon(): string {
  return pngDataUri(SIGNATURE_ICON_LINKEDIN_BASE64);
}

type ContactRow = {
  iconSrc: string;
  text: string;
  href: string;
};

// Asset-URL overrides for callers that can't use base64 data: URIs
// because the embedding target caps signature size — Gmail's
// users.settings.sendAs API enforces a 10,000-char `signature` limit,
// and the default logo alone is ~80 KB base64 (well over the cap).
// When `assetUrls` is provided every `<img src>` in the rendered
// signature points at the public HTTPS asset instead of an inline
// data: URI. When omitted (the default, used by every inbox-bound
// path — preview, /reply, /send, gmail.ts withSignature) icons and
// logo stay base64 so recipients see them without a "Load remote
// images" prompt.
export type SignatureAssetUrls = {
  iconEmail: string;
  iconPhone: string;
  iconGlobe: string;
  iconLinkedin: string;
  // When provided, replaces the profile's base64-embedded logo.
  // When undefined, the rendered signature still embeds the user's
  // logo as a data: URI (preserves custom-logo support on inbox
  // paths). Callers that need a small signature (Gmail settings)
  // should pass the hosted default-logo URL here.
  logo?: string;
};

function buildContactRows(p: UserProfileRecord, assetUrls?: SignatureAssetUrls): ContactRow[] {
  const rows: ContactRow[] = [];
  if (p.email) {
    rows.push({
      iconSrc: assetUrls?.iconEmail ?? envelopeIcon(),
      text: p.email,
      href: `mailto:${p.email}`,
    });
  }
  if (p.phone) {
    rows.push({
      iconSrc: assetUrls?.iconPhone ?? phoneIcon(),
      text: p.phone,
      href: `tel:${p.phone.replace(/[^+0-9]/g, "")}`,
    });
  }
  if (p.website) {
    const href = /^https?:\/\//i.test(p.website) ? p.website : `https://${p.website}`;
    rows.push({
      iconSrc: assetUrls?.iconGlobe ?? globeIcon(),
      text: p.website,
      href,
    });
  }
  // Company LinkedIn — always the bottom row (constant URL, label
  // reads "LinkedIn" rather than the long /company/ path).
  rows.push({
    iconSrc: assetUrls?.iconLinkedin ?? linkedinIcon(),
    text: "LinkedIn",
    href: LINKEDIN_URL,
  });
  return rows;
}

// Unique sentinel that marks an Ace-rendered HTML signature in an
// email body. HTML comments are invisible to recipients but survive
// round-trips through our own send/draft pipeline, which lets
// withSignature detect (and strip) a prior Ace signature before
// appending a fresh one. Without this, any flow that fed an
// already-signed body back through withSignature would double-sign
// the email — the symptom Andrew hit where sent mail rendered two
// stacked logo + contact-icon blocks.
export const ACE_SIGNATURE_MARKER = "<!--ace-signature-->";

// Render the signature as an HTML-table block. Returns just the inner
// HTML (no <html><body>) so callers can splice it into any email body.
//
// `assetUrls` is an optional override for callers that can't afford
// inline base64 image bytes (see SignatureAssetUrls). Inbox-bound
// callers (composer, preview, /send, /reply) pass nothing and get
// the default base64-embedded output. The Push-to-Gmail action
// passes hosted URLs so the resulting signature fits inside Gmail
// API's 10,000-char `signature` limit.
export function renderSignatureHtml(
  profile: UserProfileRecord,
  assetUrls?: SignatureAssetUrls,
): string {
  // Logo: prefer the caller-provided hosted URL when given (Gmail
  // push). Otherwise fall back to the profile's base64-embedded
  // bytes — the inbox-side behavior that ships with every Ace email.
  const logoSrc = assetUrls?.logo
    ? assetUrls.logo
    : profile.logoDataBase64.length > 0
      ? `data:${profile.logoMimeType};base64,${profile.logoDataBase64}`
      : "";
  const contactRows = buildContactRows(profile, assetUrls);
  const nameLine = profile.fullName
    ? `<div style="font-family: Georgia, 'Cormorant Garamond', serif; font-weight: 700; font-size: 18px; color: ${SIGNATURE_DARK}; line-height: 1.2;">${escape(profile.fullName)}</div>`
    : "";
  const titleLine = profile.jobTitle
    ? `<div style="font-family: Arial, Helvetica, sans-serif; font-weight: 700; font-size: 11px; color: ${SIGNATURE_GREEN}; letter-spacing: 1.5px; text-transform: uppercase; margin-top: 4px;">${escape(profile.jobTitle)}</div>`
    : "";
  const divider = `<div style="border-top: 1px solid ${SIGNATURE_DIVIDER}; margin: 8px 0;"></div>`;
  const contactsHtml = contactRows
    .map(
      (r) => `
        <tr>
          <td style="padding: 2px 8px 2px 0; vertical-align: middle;">
            <img src="${r.iconSrc}" width="20" height="20" alt="" style="display: block; border: 0;"/>
          </td>
          <td style="padding: 2px 0; vertical-align: middle; font-family: Arial, Helvetica, sans-serif; font-size: 13px; color: ${SIGNATURE_DARK};">
            <a href="${escape(r.href)}" style="color: ${SIGNATURE_DARK}; text-decoration: underline;">${escape(r.text)}</a>
          </td>
        </tr>`,
    )
    .join("");

  const logoCell = logoSrc
    ? `
      <td width="140" style="padding: 0 18px 0 0; vertical-align: middle; background: #ffffff;">
        <img src="${logoSrc}" width="120" alt="BreakPoint Talent" style="display: block; border: 0; max-width: 120px; height: auto;"/>
      </td>`
    : "";

  const dividerCell = `
    <td width="2" style="width: 2px; background: ${SIGNATURE_GREEN}; padding: 0;">&nbsp;</td>`;

  return `${ACE_SIGNATURE_MARKER}<table role="presentation" cellpadding="0" cellspacing="0" border="0" style="border-collapse: collapse; font-family: Arial, Helvetica, sans-serif; color: ${SIGNATURE_DARK};">
      <tr>
        ${logoCell}
        ${dividerCell}
        <td style="padding: 0 0 0 18px; vertical-align: middle;">
          ${nameLine}
          ${titleLine}
          ${nameLine || titleLine ? divider : ""}
          <table role="presentation" cellpadding="0" cellspacing="0" border="0" style="border-collapse: collapse;">
            ${contactsHtml}
          </table>
        </td>
      </tr>
    </table>`;
}

// One embedded signature image, ready to attach as a multipart/related
// inline MIME part. `cid` is the Content-ID token: the HTML references it
// as `cid:<cid>` and the part header carries `Content-ID: <<cid>>`.
export type SignatureInlineImage = {
  cid: string;
  mimeType: string;
  base64: string;
  filename: string;
};

// Render the signature with `cid:` image references and return the inline
// image parts the send pipeline must embed as a multipart/related sibling.
//
// Why this exists (and why inbox sends use it instead of the data:-URI
// variant above): renderSignatureHtml embeds the logo + icons as base64
// `data:` URIs. Gmail rewrites every `data:` URI into a `cid:` MIME image
// part on send and labels the logo part with a filename (taken from the
// img alt text), which makes Apple Mail / iOS Mail render the logo a
// SECOND time as a bottom attachment thumbnail — the "duplicate signature"
// Andrew saw. Gmail itself renders inline-only, hiding the bug there.
//
// Emitting our OWN inline parts with `Content-Disposition: inline` keeps
// the images embedded (no "load remote images" prompt) and renders the
// signature exactly once in every client. Gmail leaves our cid: parts
// alone because there is no data: URI left to rewrite.
export function renderSignatureInline(
  profile: UserProfileRecord,
  cidPrefix: string,
): { html: string; images: SignatureInlineImage[] } {
  const images: SignatureInlineImage[] = [];
  const logoCid = `${cidPrefix}-logo`;
  const emailCid = `${cidPrefix}-email`;
  const phoneCid = `${cidPrefix}-phone`;
  const globeCid = `${cidPrefix}-globe`;
  const linkedinCid = `${cidPrefix}-linkedin`;

  const hasLogo = profile.logoDataBase64.length > 0;
  if (hasLogo) {
    images.push({
      cid: logoCid,
      mimeType: profile.logoMimeType || "image/png",
      base64: profile.logoDataBase64,
      filename: "breakpoint-logo.png",
    });
  }
  // Icons are pushed only for the contact rows that actually render, so the
  // cid: refs in the HTML and the attached parts stay 1:1 (buildContactRows
  // emits a row only when the field is present).
  if (profile.email) {
    images.push({ cid: emailCid, mimeType: SIGNATURE_ICON_MIME, base64: SIGNATURE_ICON_EMAIL_BASE64, filename: "email.png" });
  }
  if (profile.phone) {
    images.push({ cid: phoneCid, mimeType: SIGNATURE_ICON_MIME, base64: SIGNATURE_ICON_PHONE_BASE64, filename: "phone.png" });
  }
  if (profile.website) {
    images.push({ cid: globeCid, mimeType: SIGNATURE_ICON_MIME, base64: SIGNATURE_ICON_GLOBE_BASE64, filename: "website.png" });
  }
  // LinkedIn row always renders (constant company link), so its inline
  // image is always attached - keeps the cid: refs and parts 1:1.
  images.push({ cid: linkedinCid, mimeType: SIGNATURE_ICON_MIME, base64: SIGNATURE_ICON_LINKEDIN_BASE64, filename: "linkedin.png" });

  const html = renderSignatureHtml(profile, {
    iconEmail: `cid:${emailCid}`,
    iconPhone: `cid:${phoneCid}`,
    iconGlobe: `cid:${globeCid}`,
    iconLinkedin: `cid:${linkedinCid}`,
    logo: hasLogo ? `cid:${logoCid}` : undefined,
  });
  return { html, images };
}

export function renderSignatureText(profile: UserProfileRecord): string {
  const lines: string[] = [];
  if (profile.fullName) lines.push(profile.fullName);
  if (profile.jobTitle) lines.push(profile.jobTitle);
  if (profile.email) lines.push(profile.email);
  if (profile.phone) lines.push(profile.phone);
  if (profile.website) lines.push(profile.website);
  lines.push(`LinkedIn: ${LINKEDIN_URL}`);
  return lines.join("\n");
}

function escape(raw: string): string {
  return raw
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

// Standard email signature delimiter per RFC 3676: "-- " (dash-dash-
// space) on a line by itself. Used by mail clients to auto-fold the
// signature in quoted replies.
export const SIGNATURE_DELIMITER_TEXT = "-- ";
export const SIGNATURE_DELIMITER_HTML = `<div>-- </div>`;
