import { prisma } from "@/lib/prisma";
import { DEFAULT_BRAND_LOGO_BASE64, DEFAULT_BRAND_LOGO_MIME } from "@/lib/default-brand-logo";
import {
  SIGNATURE_ICON_EMAIL_BASE64,
  SIGNATURE_ICON_GLOBE_BASE64,
  SIGNATURE_ICON_MIME,
  SIGNATURE_ICON_PHONE_BASE64,
} from "@/lib/signature-icons";

// Gmail-style HTML-table signature rendered from the user's UserProfile.
// Kept intentionally in one file so the render logic, the plain-text
// fallback, and the default-profile bootstrap are easy to grep for.
//
// Design principles:
// - HTML tables for layout (Gmail, Apple Mail, Outlook all handle tables
//   consistently; flexbox/grid are hit-or-miss in email clients).
// - Inline styles only — <style> blocks and class refs get stripped by
//   most email clients.
// - Logo as base64 data: URI so the recipient doesn't have to click
//   "Display images from this sender" to see it.
// - Icons as SVG data: URIs. Same reason + they stay crisp at any DPI.

export const SIGNATURE_GREEN = "#5A9642";
export const SIGNATURE_DARK = "#1a1a1a";
export const SIGNATURE_DIVIDER = "#e5e7eb";
export const MAX_LOGO_BYTES = 500 * 1024;

export type UserProfileInput = {
  fullName: string;
  jobTitle: string;
  phone: string;
  website: string;
  logoDataBase64: string; // empty string means "no logo"
  logoMimeType: string;
};

export type UserProfileRecord = UserProfileInput & {
  userId: string;
  email: string;
  hasCustomLogo: boolean;
};

const ANDREW_DEFAULTS = {
  jobTitle: "Managing Partner & Founder",
  phone: "216-870-4655",
  website: "www.breakpointtalent.com",
};

// Default signature logo lives in src/lib/default-brand-logo.ts as a
// base64 constant compiled into the bundle. Reading from /public at
// runtime fails on Vercel serverless (the /public dir isn't shipped in
// the function bundle), so we never touch the filesystem here.
function loadDefaultLogo(): { mime: string; base64: string } {
  return { mime: DEFAULT_BRAND_LOGO_MIME, base64: DEFAULT_BRAND_LOGO_BASE64 };
}

// Fetch the user's profile, returning a fully-populated record with
// sensible defaults for missing fields. Never returns null; a signed-in
// user without a profile row gets a virtual one synthesized from their
// User row + /public/brand/ default logo.
export async function getUserBrandingProfile(userId: string): Promise<UserProfileRecord> {
  const user = await prisma.user.findUnique({
    where: { id: userId },
    select: { id: true, name: true, email: true, profile: true },
  });
  if (!user) {
    // Shouldn't happen in practice — caller already verified the session.
    // Fall back to the BreakPoint defaults so we never return null.
    const def = loadDefaultLogo();
    return {
      userId,
      email: "",
      fullName: "",
      jobTitle: ANDREW_DEFAULTS.jobTitle,
      phone: ANDREW_DEFAULTS.phone,
      website: ANDREW_DEFAULTS.website,
      logoDataBase64: def.base64,
      logoMimeType: def.mime,
      hasCustomLogo: false,
    };
  }
  const p = user.profile;
  const hasCustomLogo = Boolean(p?.logoData && p.logoData.length > 0);
  let logoDataBase64 = "";
  let logoMimeType = "";
  if (hasCustomLogo) {
    logoDataBase64 = Buffer.from(p!.logoData!).toString("base64");
    logoMimeType = p!.logoMimeType ?? "image/png";
  } else {
    const def = loadDefaultLogo();
    logoDataBase64 = def.base64;
    logoMimeType = def.mime;
  }
  return {
    userId: user.id,
    email: user.email ?? "",
    fullName: p?.fullName?.trim() || user.name?.trim() || "",
    jobTitle: p?.jobTitle?.trim() || ANDREW_DEFAULTS.jobTitle,
    phone: p?.phone?.trim() || ANDREW_DEFAULTS.phone,
    website: p?.website?.trim() || ANDREW_DEFAULTS.website,
    logoDataBase64,
    logoMimeType,
    hasCustomLogo,
  };
}

// PNG data: URI helpers. Switched from inline SVG to base64 PNG in
// Phase 6.5 because Gmail (and a handful of webmail clients) silently
// strips inline SVG src= refs, which left the icons rendering as empty
// outlined boxes in delivered email. PNG data URIs render reliably
// across every major client. Source bytes live in
// src/lib/signature-icons.ts (generated by scripts/generate-signature-
// icons.js — re-run that script if the artwork changes).
function pngDataUri(base64: string): string {
  return `data:${SIGNATURE_ICON_MIME};base64,${base64}`;
}

function envelopeIcon(): string {
  return pngDataUri(SIGNATURE_ICON_EMAIL_BASE64);
}

function phoneIcon(): string {
  return pngDataUri(SIGNATURE_ICON_PHONE_BASE64);
}

function globeIcon(): string {
  return pngDataUri(SIGNATURE_ICON_GLOBE_BASE64);
}

type ContactRow = {
  iconSrc: string;
  text: string;
  href: string;
};

function buildContactRows(p: UserProfileRecord): ContactRow[] {
  const rows: ContactRow[] = [];
  if (p.email) {
    rows.push({ iconSrc: envelopeIcon(), text: p.email, href: `mailto:${p.email}` });
  }
  if (p.phone) {
    rows.push({
      iconSrc: phoneIcon(),
      text: p.phone,
      href: `tel:${p.phone.replace(/[^+0-9]/g, "")}`,
    });
  }
  if (p.website) {
    const href = /^https?:\/\//i.test(p.website) ? p.website : `https://${p.website}`;
    rows.push({ iconSrc: globeIcon(), text: p.website, href });
  }
  return rows;
}

// Unique sentinel that marks an Ace-rendered HTML signature in an
// email body. HTML comments are invisible to recipients but survive
// round-trips through our own send/draft pipeline, which lets
// withSignature detect (and strip) a prior Ace signature before
// appending a fresh one. Without this, any flow that fed an
// already-signed body back through withSignature would double-sign
// the email — the symptom Andrew hit where sent mail rendered two
// stacked logo + contact-icon blocks.
export const ACE_SIGNATURE_MARKER = "<!--ace-signature-->";

// Render the signature as an HTML-table block. Returns just the inner
// HTML (no <html><body>) so callers can splice it into any email body.
export function renderSignatureHtml(profile: UserProfileRecord): string {
  const logoSrc =
    profile.logoDataBase64.length > 0
      ? `data:${profile.logoMimeType};base64,${profile.logoDataBase64}`
      : "";
  const contactRows = buildContactRows(profile);
  const nameLine = profile.fullName
    ? `<div style="font-family: Georgia, 'Cormorant Garamond', serif; font-weight: 700; font-size: 18px; color: ${SIGNATURE_DARK}; line-height: 1.2;">${escape(profile.fullName)}</div>`
    : "";
  const titleLine = profile.jobTitle
    ? `<div style="font-family: Arial, Helvetica, sans-serif; font-weight: 700; font-size: 11px; color: ${SIGNATURE_GREEN}; letter-spacing: 1.5px; text-transform: uppercase; margin-top: 4px;">${escape(profile.jobTitle)}</div>`
    : "";
  const divider = `<div style="border-top: 1px solid ${SIGNATURE_DIVIDER}; margin: 8px 0;"></div>`;
  const contactsHtml = contactRows
    .map(
      (r) => `
        <tr>
          <td style="padding: 2px 8px 2px 0; vertical-align: middle;">
            <img src="${r.iconSrc}" width="20" height="20" alt="" style="display: block; border: 0;"/>
          </td>
          <td style="padding: 2px 0; vertical-align: middle; font-family: Arial, Helvetica, sans-serif; font-size: 13px; color: ${SIGNATURE_DARK};">
            <a href="${escape(r.href)}" style="color: ${SIGNATURE_DARK}; text-decoration: underline;">${escape(r.text)}</a>
          </td>
        </tr>`,
    )
    .join("");

  const logoCell = logoSrc
    ? `
      <td width="140" style="padding: 0 18px 0 0; vertical-align: middle; background: #ffffff;">
        <img src="${logoSrc}" width="120" alt="BreakPoint Talent" style="display: block; border: 0; max-width: 120px; height: auto;"/>
      </td>`
    : "";

  const dividerCell = `
    <td width="2" style="width: 2px; background: ${SIGNATURE_GREEN}; padding: 0;">&nbsp;</td>`;

  return `${ACE_SIGNATURE_MARKER}<table role="presentation" cellpadding="0" cellspacing="0" border="0" style="border-collapse: collapse; font-family: Arial, Helvetica, sans-serif; color: ${SIGNATURE_DARK};">
      <tr>
        ${logoCell}
        ${dividerCell}
        <td style="padding: 0 0 0 18px; vertical-align: middle;">
          ${nameLine}
          ${titleLine}
          ${nameLine || titleLine ? divider : ""}
          <table role="presentation" cellpadding="0" cellspacing="0" border="0" style="border-collapse: collapse;">
            ${contactsHtml}
          </table>
        </td>
      </tr>
    </table>`;
}

export function renderSignatureText(profile: UserProfileRecord): string {
  const lines: string[] = [];
  if (profile.fullName) lines.push(profile.fullName);
  if (profile.jobTitle) lines.push(profile.jobTitle);
  if (profile.email) lines.push(profile.email);
  if (profile.phone) lines.push(profile.phone);
  if (profile.website) lines.push(profile.website);
  return lines.join("\n");
}

function escape(raw: string): string {
  return raw
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

// Standard email signature delimiter per RFC 3676: "-- " (dash-dash-
// space) on a line by itself. Used by mail clients to auto-fold the
// signature in quoted replies.
export const SIGNATURE_DELIMITER_TEXT = "-- ";
export const SIGNATURE_DELIMITER_HTML = `<div>-- </div>`;
