"use client";

import { useEffect, useRef, useState } from "react";
import { Sparkles } from "lucide-react";

// Companion to WordOfDayCard. Renders a chip in the dashboard bottom
// bar; clicking opens a popover with today's quote, the author, and
// a one-sentence context line. /api/quote-of-day caches one row per
// (org, ET day) so repeat loads don't re-spend Claude.

type QuotePayload = {
  quote: string;
  author: string;
  context: string;
};

type ApiResponse =
  | (QuotePayload & { ok: true; cached?: boolean })
  | { ok: false; error: string };

export function QuoteOfDay() {
  const [data, setData] = useState<QuotePayload | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [open, setOpen] = useState(false);

  const containerRef = useRef<HTMLDivElement | null>(null);

  useEffect(() => {
    let cancelled = false;
    void (async () => {
      try {
        const res = await fetch("/api/quote-of-day", { cache: "no-store" });
        const json = (await res.json()) as ApiResponse;
        if (cancelled) return;
        if (!res.ok || !json.ok) {
          setError("ok" in json && !json.ok ? json.error : `HTTP ${res.status}`);
          return;
        }
        setData({
          quote: json.quote,
          author: json.author,
          context: json.context,
        });
      } catch (e) {
        if (!cancelled) {
          setError(e instanceof Error ? e.message : "Failed to load");
        }
      }
    })();
    return () => {
      cancelled = true;
    };
  }, []);

  useEffect(() => {
    if (!open) return;
    function onDown(e: MouseEvent) {
      const node = containerRef.current;
      if (!node) return;
      if (!node.contains(e.target as Node)) setOpen(false);
    }
    function onKey(e: KeyboardEvent) {
      if (e.key === "Escape") setOpen(false);
    }
    document.addEventListener("mousedown", onDown);
    document.addEventListener("keydown", onKey);
    return () => {
      document.removeEventListener("mousedown", onDown);
      document.removeEventListener("keydown", onKey);
    };
  }, [open]);

  if (!data) {
    if (error) return null;
    return null;
  }

  return (
    <div ref={containerRef} className="relative">
      <button
        type="button"
        onClick={() => setOpen((v) => !v)}
        aria-expanded={open}
        aria-haspopup="dialog"
        className="inline-flex items-center gap-1.5 rounded-md border border-court-border bg-court-surface px-3 py-1.5 text-xs font-medium text-court-fg-muted transition hover:border-court-accent/40 hover:text-court-fg"
      >
        <span aria-hidden="true">💬</span>
        <span>Quote of the Day</span>
      </button>

      {open && (
        <div
          role="dialog"
          aria-label="Quote of the Day"
          className="absolute bottom-full left-0 z-20 mb-2 w-80 rounded-xl border border-court-border bg-court-surface p-4 shadow-xl dark:shadow-[0_0_0_1px_rgba(255,255,255,0.06),0_8px_32px_rgba(0,0,0,0.4)]"
        >
          <div className="text-[10px] font-semibold uppercase tracking-widest text-court-fg-muted">
            Quote of the Day
          </div>
          <blockquote className="mt-2 text-sm leading-relaxed text-court-fg [text-wrap:pretty]">
            &ldquo;{data.quote}&rdquo;
          </blockquote>
          <div className="mt-3 text-sm font-semibold text-court-fg">
            {data.author}
          </div>
          <div className="mt-1 text-xs italic leading-relaxed text-court-fg-muted">
            {data.context}
          </div>
          <div className="mt-3 flex items-center gap-1 text-[10px] uppercase tracking-wider text-court-fg-muted">
            <Sparkles className="h-3 w-3" /> Generated by Ace
          </div>
        </div>
      )}
    </div>
  );
}
