"use client";

import { useEffect, useState } from "react";
import { Sparkles } from "lucide-react";

// Daily vocabulary card for the dashboard. Mounts on the client so the
// /api/word-of-day call doesn't block server-side dashboard render —
// the card shows a skeleton, then swaps in the JSON when the route
// resolves. Same row as the KPI tiles at xl; stacks below on smaller
// breakpoints (handled by the parent layout).

type WordPayload = {
  word: string;
  partOfSpeech: string;
  definition: string;
  exampleSentence: string;
};

type ApiResponse =
  | (WordPayload & { ok: true; cached?: boolean })
  | { ok: false; error: string };

export function WordOfDayCard() {
  const [data, setData] = useState<WordPayload | null>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    let cancelled = false;
    void (async () => {
      try {
        const res = await fetch("/api/word-of-day", { cache: "no-store" });
        const json = (await res.json()) as ApiResponse;
        if (cancelled) return;
        if (!res.ok || !json.ok) {
          setError("ok" in json && !json.ok ? json.error : `HTTP ${res.status}`);
          return;
        }
        setData({
          word: json.word,
          partOfSpeech: json.partOfSpeech,
          definition: json.definition,
          exampleSentence: json.exampleSentence,
        });
      } catch (e) {
        if (!cancelled) {
          setError(e instanceof Error ? e.message : "Failed to load");
        }
      }
    })();
    return () => {
      cancelled = true;
    };
  }, []);

  return (
    <div className="flex h-full flex-col rounded-2xl border border-court-border bg-court-surface p-5 shadow-sm">
      <div className="text-[11px] font-semibold uppercase tracking-widest text-court-fg-muted">
        Word of the Day
      </div>
      {data ? (
        <>
          <div className="mt-2 flex items-baseline gap-2">
            <div className="font-stat text-2xl font-bold leading-tight text-court-fg">
              {data.word}
            </div>
            <div className="text-xs italic text-court-fg-muted">
              {data.partOfSpeech}
            </div>
          </div>
          <div className="mt-2 text-sm text-court-fg">{data.definition}</div>
          <div className="mt-2 text-xs italic leading-relaxed text-court-fg-muted">
            &ldquo;{data.exampleSentence}&rdquo;
          </div>
        </>
      ) : error ? (
        <div className="mt-2 text-xs text-court-fg-muted">
          Couldn&apos;t load today&apos;s word.
        </div>
      ) : (
        // Skeleton — three pulsing bars sized like word/definition/example.
        <div className="mt-3 flex flex-1 flex-col gap-2">
          <div className="h-6 w-2/3 animate-pulse rounded bg-court-surface-subtle" />
          <div className="h-3 w-full animate-pulse rounded bg-court-surface-subtle" />
          <div className="h-3 w-5/6 animate-pulse rounded bg-court-surface-subtle" />
          <div className="h-3 w-3/4 animate-pulse rounded bg-court-surface-subtle" />
        </div>
      )}
      <div className="mt-auto flex items-center gap-1 pt-3 text-[10px] uppercase tracking-wider text-court-fg-muted">
        <Sparkles className="h-3 w-3" /> Generated by Ace
      </div>
    </div>
  );
}
